export const config = {
  onBoardingFirstImage: require('../assets/images/onboardingfirst.png'),
  onBoardingSecondImage: require('../assets/images/onboardingsecond.png'),
  onBoardingThirdImage: require('../assets/images/onboardingthreepng.png'),
  loginSignupImageBg: require('../assets/images/loginSignupBgImage.png'),
  SignupBottomImage : require('../assets/images/signUpBottom.png'),
  categoryCatImage : require('../assets/images/category_cat.png'),
  categoryDogImage : require('../assets/images/category_dog.png'),
  cat1 : require('../assets/images/category_cat.png'),
  cat2 : require('../assets/images/category_cat1.png'),
  cat3 : require('../assets/images/category_cat.png'),
  cat4 : require('../assets/images/category_cat1.png'),
  cat5 : require('../assets/images/category_cat.png'),
  cat6 : require('../assets/images/category_cat.png'),
  cat7 : require('../assets/images/category_cat1.png'),
  cat8 : require('../assets/images/category_cat.png'),
  cat9 : require('../assets/images/category_cat1.png'),
  cat10: require('../assets/images/category_cat1.png'),
  dog1 : require('../assets/images/category_dog.png'),
  dog2 : require('../assets/images/category_dog.png'),
  dog3 : require('../assets/images/category_dog1.png'),
  dog4 : require('../assets/images/category_dog1.png'),
  dog5 : require('../assets/images/category_dog.png'),
  dog6 : require('../assets/images/category_dog.png'),
  dog7 : require('../assets/images/category_dog1.png'),
  dog8 : require('../assets/images/category_dog1.png'),
  dog9 : require('../assets/images/category_dog.png'),
  dog10: require('../assets/images/category_dog1.png'),
}