export const petConstants = {
    CREATE_PET_REQUEST: "CREATE_PET_REQUEST",
    CREATE_PET_ACCEPT: "CREATE_PET_ACCEPT",
    CREATE_PET_FAILURE: "CREATE_PET_FAILURE",

    GET_PETS_REQUEST: "GET_PETS_REQUEST",
    GET_PETS_ACCEPT: "GET_PETS_ACCEPT",
    GET_PETS_FAILURE: "GET_PETS_FAILURE",

    GET_MY_PETS_REQUEST: "GET_MY_PETS_REQUEST",
    GET_MY_PETS_ACCEPT: "GET_MY_PETS_ACCEPT",
    GET_MY_PETS_FAILURE: "GET_MY_PETS_FAILURE",

    UPDATE_PET_ADOPTED_REQUEST: "UPDATE_PET_ADOPTED_REQUEST",
    UPDATE_PET_ADOPTED_ACCEPT: "UPDATE_PET_ADOPTED_ACCEPT",
    UPDATE_PET_ADOPTED_FAILURE: "UPDATE_PET_ADOPTED_FAILURE",

    DELETE_PET_REQUEST: "DELETE_PET_REQUEST",
    DELETE_PET_ACCEPT: "DELETE_PET_ACCEPT",
    DELETE_PET_FAILURE: "DELETE_PET_FAILURE",
};
