export const petConstants = {
    CREATE_PET_REQUEST: "CREATE_PET_REQUEST",
    CREATE_PET_ACCEPT: "CREATE_PET_ACCEPT",
    CREATE_PET_FAILURE: "CREATE_PET_FAILURE",

    GET_PETS_REQUEST: "GET_PETS_REQUEST",
    GET_PETS_ACCEPT: "GET_PETS_ACCEPT",
    GET_PETS_FAILURE: "GET_PETS_FAILURE",
};
