export const userConstants = {
    "USER_LOGIN_REQUEST" : "USER_LOGIN_REQUEST",
    "USER_LOGIN_ACCEPT" :  "USER_LOGIN_ACCEPT",
    "USER_LOGIN_FAILURE" :  "USER_LOGIN_FAILURE",

    "USER_GOOGLE_LOGIN_REQUEST" : "USER_GOOGLE_LOGIN_REQUEST",
    "USER_GOOGLE_LOGIN_ACCEPT" :  "USER_GOOGLE_LOGIN_ACCEPT",
    "USER_GOOGLE_LOGIN_FAILURE" :  "USER_GOOGLE_LOGIN_FAILURE",

    "USER_REGISTER_REQUEST" : "USER_REGISTER_REQUEST",
    "USER_REGISTER_ACCEPT" :  "USER_REGISTER_ACCEPT",
    "USER_REGISTER_FAILURE" :  "USER_REGISTER_FAILURE",

    "USER_DETAILS_REQUEST" : "USER_DETAILS_REQUEST",
    "USER_DETAILS_ACCEPT" :  "USER_DETAILS_ACCEPT",
    "USER_DETAILS_FAILURE" :  "USER_DETAILS_FAILURE",

    "USER_UPDATE_PROFILE_REQUEST" : "USER_UPDATE_PROFILE_REQUEST",
    "USER_UPDATE_PROFILE_ACCEPT" :  "USER_UPDATE_PROFILE_ACCEPT",
    "USER_UPDATE_PROFILE_FAILURE" :  "USER_UPDATE_PROFILE_FAILURE",

    "USER_OTP_REQUEST" : "USER_OTP_REQUEST",
    "USER_OTP_ACCEPT" :  "USER_OTP_ACCEPT",
    "USER_OTP_FAILURE" :  "USER_OTP_FAILURE",

    "USER_FORGOT_PASSWORD_REQUEST" : "USER_FORGOT_PASSWORD_REQUEST",
    "USER_FORGOT_PASSWORD_ACCEPT" :  "USER_FORGOT_PASSWORD_ACCEPT",
    "USER_FORGOT_PASSWORD_FAILURE" :  "USER_FORGOT_PASSWORD_FAILURE",

    "USER_FORGOT_PASSWORD_OTP_REQUEST" : "USER_FORGOT_PASSWORD_OTP_REQUEST",
    "USER_FORGOT_PASSWORD_OTP_ACCEPT" :  "USER_FORGOT_PASSWORD_OTP_ACCEPT",
    "USER_FORGOT_PASSWORD_OTP_FAILURE" :  "USER_FORGOT_PASSWORD_OTP_FAILURE",

    "USER_UPDATE_PASSWORD_REQUEST" : "USER_UPDATE_PASSWORD_REQUEST",
    "USER_UPDATE_PASSWORD_ACCEPT" :  "USER_UPDATE_PASSWORD_ACCEPT",
    "USER_UPDATE_PASSWORD_FAILURE" :  "USER_UPDATE_PASSWORD_FAILURE",
    
}