export const userConstants = {
    "USER_LOGIN_REQUEST" : "USER_LOGIN_REQUEST",
    "USER_LOGIN_ACCEPT" :  "USER_LOGIN_ACCEPT",
    "USER_LOGIN_FAILURE" :  "USER_LOGIN_FAILURE",

    "USER_REGISTER_REQUEST" : "USER_REGISTER_REQUEST",
    "USER_REGISTER_ACCEPT" :  "USER_REGISTER_ACCEPT",
    "USER_REGISTER_FAILURE" :  "USER_REGISTER_FAILURE",
}